name: Deploy Website to Amen.pt

on:
  push:
    branches:
      - main  # Triggers the workflow every time you push to the 'main' branch

jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to Amen.pt
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # If Amen requires a specific folder (like public_html or web), specify it here:
        server-dir: ./public/www/game/
        
